name: TCD.Portal

on:
  push:
    branches: ["main"]
    paths:
      - 'TheCollectorsDenPortal/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'TheCollectorsDenPortal/**'
      - '.github/workflows/frontend-ci.yml'

run-name: |
  [TCD.Portal] ${{ github.event.head_commit.message || format('PR #{0} - {1}', github.event.pull_request.number, github.event.pull_request.title) }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TheCollectorsDenPortal
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npx jest
